# Generated by Django 5.0.6 on 2024-08-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lvl', models.IntegerField(default=1)),
                ('energy', models.IntegerField(default=1000)),
                ('coin', models.PositiveBigIntegerField(default=0)),
                ('crystal', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('chance', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prizes', models.ManyToManyField(related_name='box', to='main.prize')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_bonus', models.BooleanField(default=True)),
                ('new_player_bonus', models.BooleanField(default=True)),
                ('new_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_person', to='main.player')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_lvl', models.IntegerField(default=1)),
                ('price_lvl_up_energy', models.PositiveBigIntegerField(default=1000)),
                ('autobot_time', models.PositiveBigIntegerField(default=300)),
                ('autobot_lvl', models.IntegerField(default=1)),
                ('flag_autobot', models.BooleanField(default=True)),
                ('one_tap_energy', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=1)),
                ('price_lvl_up_damage_and_energy', models.PositiveBigIntegerField(default=1000)),
                ('lvl_one_tap_damage_and_energy', models.IntegerField(default=1)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade', to='main.player')),
            ],
        ),
    ]
