# Generated by Django 5.0.6 on 2024-08-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_upgrade_start_autobot_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='chance',
            field=models.FloatField(default=1),
        ),
    ]
