# Generated by Django 5.0.6 on 2024-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_prize_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
