# Generated by Django 5.0.6 on 2024-08-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_box_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='boxes',
            field=models.ManyToManyField(related_name='players', to='main.box'),
        ),
    ]
