# Generated by Django 5.0.6 on 2024-08-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_box_price_remove_player_boxes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название лиги')),
                ('min_coin', models.PositiveBigIntegerField(default=0, verbose_name='Количество монет для входа в лигу')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Цена лиги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен/неактивен')),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название коробки'),
        ),
        migrations.AlterField(
            model_name='box',
            name='prizes',
            field=models.ManyToManyField(related_name='box', to='main.prize', verbose_name='Призы'),
        ),
        migrations.AlterField(
            model_name='player',
            name='coin',
            field=models.PositiveBigIntegerField(default=1000, verbose_name='Монеты игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='crystal',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кристаллы игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=1000, verbose_name='Максимальная энергия игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lvl',
            field=models.IntegerField(default=1, verbose_name='Уровень игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='now_energy',
            field=models.IntegerField(default=1000, verbose_name='Текущая энергия игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='price_bronze_case',
            field=models.PositiveBigIntegerField(default=10000, verbose_name='Цена бронзового сундука'),
        ),
        migrations.AlterField(
            model_name='player',
            name='price_gold_case',
            field=models.PositiveBigIntegerField(default=100000, verbose_name='Цена золотого сундука'),
        ),
        migrations.AlterField(
            model_name='player',
            name='price_silver_case',
            field=models.PositiveBigIntegerField(default=30000, verbose_name='Цена серебренного сундука'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tg_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='chance',
            field=models.FloatField(default=1, verbose_name='Шанс выпадения'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название приза'),
        ),
        migrations.AlterField(
            model_name='referralsystem',
            name='new_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_person', to='main.player', verbose_name='Новый игрок'),
        ),
        migrations.AlterField(
            model_name='referralsystem',
            name='new_player_bonus',
            field=models.BooleanField(default=True, verbose_name='Бонус нового игрока'),
        ),
        migrations.AlterField(
            model_name='referralsystem',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='main.player', verbose_name='Реферал'),
        ),
        migrations.AlterField(
            model_name='referralsystem',
            name='referral_bonus',
            field=models.BooleanField(default=True, verbose_name='Бонус реферала'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='autobot_lvl',
            field=models.IntegerField(default=1, verbose_name='Уровень автобота'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='autobot_time',
            field=models.PositiveBigIntegerField(default=300, verbose_name='Время автобота'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='coin_bonus_result',
            field=models.IntegerField(default=0, verbose_name='Бонус монет'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='damage',
            field=models.IntegerField(default=1, verbose_name='Урон'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='energy_lvl',
            field=models.IntegerField(default=1, verbose_name='Уровень энергии игрока'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='flag_autobot',
            field=models.BooleanField(default=True, verbose_name='Флаг автобота'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='lvl_one_tap_damage_and_energy',
            field=models.IntegerField(default=1, verbose_name='Уровень урона и энергии за одно нажатие'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='one_tap_energy',
            field=models.IntegerField(default=1, verbose_name='Энергия за одно нажатие'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade', to='main.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='price_lvl_up_damage_and_energy',
            field=models.PositiveBigIntegerField(default=1000, verbose_name='Цена повышения уровня урона и энергии'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='price_lvl_up_energy',
            field=models.PositiveBigIntegerField(default=1000, verbose_name='Цена повышения уровня энергии'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='start_autobot_time',
            field=models.PositiveBigIntegerField(default=300, verbose_name='Начальное время автобота'),
        ),
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.league', verbose_name='Лига игрока'),
        ),
    ]
