# Generated by Django 5.0.6 on 2024-08-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_league_alter_box_name_alter_box_prizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSkins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prize', models.IntegerField(blank=True, null=True, verbose_name='ID приза из БД')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_prizes', to='main.player', verbose_name='Игрок')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_prizes', to='main.prize', verbose_name='Приз')),
            ],
        ),
    ]
