# Generated by Django 5.0.6 on 2024-09-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_box_is_active_playerskins_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskplayer',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='players_task', to='main.player', verbose_name='Игрок'),
        ),
    ]
