# Generated by Django 5.0.6 on 2024-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_taskplayer_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplayer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт выполнения задачи'),
        ),
    ]
