# Generated by Django 5.0.6 on 2024-09-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_player_boxes_available_player_show_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerskins',
            name='available_skin',
            field=models.BooleanField(default=False, verbose_name='Доступен/недоступен пользователю'),
        ),
        migrations.AddField(
            model_name='playerskins',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Нынешний скин'),
        ),
        migrations.AlterField(
            model_name='playerskins',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_skins', to='main.player', verbose_name='Игрок'),
        ),
        migrations.CreateModel(
            name='LeagueSkins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Название скина')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Описание скина')),
                ('available_skin', models.BooleanField(default=False, verbose_name='Доступен/недоступен пользователю')),
                ('is_active', models.BooleanField(default=False, verbose_name='Нынешний скин')),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_skin', to='main.league', verbose_name='Лига скина')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_skins', to='main.player', verbose_name='Игрок')),
            ],
        ),
    ]
