# Generated by Django 5.0.6 on 2024-09-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_playerskins_available_skin_playerskins_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueskins',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_skins', to='main.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='playerskins',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_skins', to='main.player', verbose_name='Игрок'),
        ),
    ]
