# Generated by Django 5.0.6 on 2024-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_leagueskins_player_alter_playerskins_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueskins',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerskins',
            name='player',
        ),
        migrations.AddField(
            model_name='leagueskins',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, related_name='league_skins', to='main.player', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playerskins',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, related_name='player_skins', to='main.player', verbose_name='Игрок'),
        ),
    ]
