# Generated by Django 5.0.6 on 2024-09-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_leagueskins_player_alter_playerskins_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerskins',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerskins',
            name='prize',
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prize', models.IntegerField(blank=True, null=True, verbose_name='ID приза из БД')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Название скина')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Описание скина')),
                ('available_skin', models.BooleanField(default=False, verbose_name='Доступен/недоступен пользователю')),
                ('is_active', models.BooleanField(default=False, verbose_name='Нынешний скин')),
                ('skin_type', models.CharField(choices=[('player', 'Сундук'), ('league', 'Лига')], default='player', max_length=10, verbose_name='Тип скина')),
                ('league', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin', to='main.league', verbose_name='Лига скина')),
                ('player', models.ManyToManyField(blank=True, related_name='skins', to='main.player', verbose_name='Игрок')),
                ('prizes', models.ManyToManyField(blank=True, related_name='skins', to='main.prize', verbose_name='Призы')),
            ],
        ),
        migrations.DeleteModel(
            name='LeagueSkins',
        ),
        migrations.DeleteModel(
            name='PlayerSkins',
        ),
    ]
