# Generated by Django 5.0.6 on 2024-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_player_friend_lvl_2_player_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskplayer',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='taskplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='taskplayer',
            name='start_time',
        ),
        migrations.AddField(
            model_name='player',
            name='task_X',
            field=models.BooleanField(default=False, verbose_name='Подписка на X'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_instagram',
            field=models.BooleanField(default=False, verbose_name='Подписка на инстаграм'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_tg_channel',
            field=models.BooleanField(default=False, verbose_name='Подписка на TG канал'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_tg_group',
            field=models.BooleanField(default=False, verbose_name='Подписка на TG группу'),
        ),
        migrations.AlterField(
            model_name='taskplayer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Название задачи'),
        ),
        migrations.CreateModel(
            name='PlayerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено/не выполнено')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Старт выполнения задачи')),
                ('add_flag', models.BooleanField(default=False, verbose_name='Доп. флаг')),
                ('player', models.ManyToManyField(related_name='task_player', to='main.player', verbose_name='Игрок')),
                ('task', models.ManyToManyField(related_name='player_tasks', to='main.taskplayer', verbose_name='Задача')),
            ],
        ),
    ]
