# Generated by Django 5.0.6 on 2024-09-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_player_task_x_remove_player_task_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skin',
            name='available_skin',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='player',
        ),
        migrations.CreateModel(
            name='PlayerSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_skin', models.BooleanField(default=False, verbose_name='Доступен/недоступен пользователю')),
                ('is_active', models.BooleanField(default=False, verbose_name='Нынешний скин')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_skins', to='main.player', verbose_name='Игрок')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_skins', to='main.skin', verbose_name='Скин')),
            ],
        ),
    ]
