# Generated by Django 5.0.6 on 2024-09-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_skin_available_skin_remove_skin_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый игрок/не новый'),
        ),
    ]
